# Generated by Django 2.0.3 on 2018-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qstest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
